Cu 86b14ty5d
La-azul-y-oro/proyecto_final pull request #31
Opened 2024-07-13 16:53 UTC by JuanSchiavoni

2024-07-13 16:53 UTC, gabopereyra commented
Task linked: [CU-86b14ty5d Crear endpoints Pago](https://app.clickup.com/t/86b14ty5d)

2024-07-13 17:02 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/dto/PayRequestDto.java
> +    //@NotBlank(message = "{request.invalid,blank}")
Que onda este anotacion comentada? Por otro lado, en el pago faltaria recibir los IDs de los servicios a abonar,

2024-07-13 17:03 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/dto/PayResponseDto.java
> +    private PaymentTypeResponseDto paymentTypeResponseDto;
¿¿Nos interesa saber tambien que servicios vinculados hay al pago en la respuesta??? no hemos llegado a armar los endpoints de servicios y sus correspondientes dtos, pero aprovecho a preguntar para ver si esto el dia de mañana tocara refactorizarlo para agregarlo

2024-07-13 17:05 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/service/BrandService.java
> -        if (brandRepository.existsById(id)) {
Se te escapo un agregado de espaciados aca, jajajaja
P.D: ni te moleste en ajustarlo, pero digo "que se toco en brand?" y eran esas boludeces que para GIT ya son cambios

2024-07-13 17:07 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/service/PayService.java
> +                .orElseThrow(()-> new EntityNotFoundException(MessageUtil.entityNotFound(payDto.getPaymentTypeId())));
Acá hay que ajustar, creo Santi agrego una excepcion personalizada para lanzar cuando la entidad relacionada no es valida, que dicho sea de paso, no es solo ver que exista sino tambien validar que este activa (isDeleted = false)

2024-07-13 17:07 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/service/PayService.java
> +                .orElseThrow(()-> new EntityNotFoundException(MessageUtil.entityNotFound(payDto.getPaymentTypeId())));
Tambien tocara agregar lo de los servicios a vincular, que te mencione en el request

2024-07-13 17:07 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/service/PayService.java
> +                .orElseThrow(()-> new EntityNotFoundException(MessageUtil.entityNotFound(dto.getPaymentTypeId())));
Mismos comentarios que en la parte del create

2024-07-13 17:10 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/service/PayService.java
> +            payRepository.softDelete(id);
¿Y que ocurre con los servicios que estan activos? quedan vinculados a esta entidad (via tabla intermedia) o habria que darle una vuelta de tuerca para eliminar esos datos?
Pienso en lo siguiente, tiene sentido que un pago se pueda dar de baja, ya que le erraste y al servicio X le queres vincular otro pago, el tema es que pasa en esa tabla intermedia
Espero haberme dado a entender 😅

2024-07-13 17:11 UTC, gabopereyra requested changes
@JuanSchiavoni ahi te deje varios comments para que te entretengas, jajaja, avisame cualquier cosa

2024-07-14 17:40 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/dto/PayRequestDto.java
> +    private LocalDate date;
@JuanSchiavoni busque data para este caso y podrias utilizar una anotacion que es **PastOrPresent**, basicamente la misma va a pedir que la fecha que cargues sea la de hoy o previa a la de hoy

2024-07-15 20:11 UTC, JuanSchiavoni commented on back/src/main/java/com/azulyoro/back/dto/PayResponseDto.java
> +    private PaymentTypeResponseDto paymentTypeResponseDto;
me pareceria q si, tengo q agregarlo hora o cuando se cree el endpoint de servicio?

2024-07-15 20:13 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/dto/PayResponseDto.java
> +    private PaymentTypeResponseDto paymentTypeResponseDto;
Toca agregarlo cuando se haga lo de servicios, asi que despreocupate @JuanSchiavoni

2024-07-16 13:50 UTC, gabopereyra commented on back/src/main/java/com/azulyoro/back/service/PayService.java
> +    private void validateServices(List<Long> servicesIds){
@JuanSchiavoni en este metodo en lugar de lanzar EntityNotFoundException y luego IllegalArgumentException, cambia para que la excepcion lanzada sea: EntityNotFoundOrInactiveException, para este caso fijate que en la clase MessageUtil dejamos un mensaje armado, en resumen cuando la lances te qeudara una cosa asi:
 **throw new EntityNotFoundOrInactiveException(MessageUtil.entityNotFoundOrInactive(id));**

Para el caso del pago que ya esta asociado, lo sacaria por el momento, porque va a traer bardo con el update, creamos otro ticket para el dia de mañana ajustar eso, asi no se complica mas el tema. De utlima comenta el codigo y agregale una leyenda con TODO, para que nos quede marcado y no olvidarnos

2024-07-16 13:51 UTC, JuanSchiavoni commented on back/src/main/java/com/azulyoro/back/service/PayService.java
> +    private void validateServices(List<Long> servicesIds){
bien, ahi corrijo y vuelvo a mandar

2024-07-16 13:52 UTC, gabopereyra approved these changes
@JuanSchiavoni ahi te deje un comentario sobre el metodo validateServices
Ajustate ese y ya pasalo a develop (lo dejo approve)

P.D: a modo general, ojo con los rebases, porque en el ultimo push que hiciste salta como que hiciste cambios en el front que Nico habia agregado en develop.

2024-07-16 15:10 UTC, merged