CU-86b1h65jc: fixed Services table
La-azul-y-oro/proyecto_final pull request #63
Opened 2024-08-02 18:55 UTC by santiceron

fixed Services table, now shows information correctly

2024-08-02 18:55 UTC, gabopereyra commented
Task linked: [CU-86b1h65jc Tabla servicios no muestra informacion de manera correcta](https://app.clickup.com/t/86b1h65jc)

2024-08-02 22:27 UTC, gabopereyra requested changes
Fijate que se escapo el componente "serviceFormComponent" estaria bueno limpiarlo para no ensuciar el historial

Por otro lado, solo a modo de comentarios:
- las clases de tests las estamos volando, veo que junto al serviceFormComponent, esta el spec.ts, si cuando generas los componentes con el cliente queres evitar que se cree la misma podes tirar el comando con la bandera --skip-tests

- sobre el texto del commit, siguiendo la regla que se viene aplicando, seria mas acorde: "fix(CU-xxxxxxxx):  services table", solo como para seguir incorporando esa maña nada mas

2024-08-03 15:25 UTC, santiceron commented
Hecho!

2024-08-03 15:26 UTC, gabopereyra approved these changes

2024-08-03 15:31 UTC, merged